# Optimization Task
num_feature_basis_functions: 1
trajectory_duration: 8.0
num_time_steps: 20 #40#20
publish_trajectory_markers: False
publish_best_trajectory_marker: True


# STOMP 
max_iterations: 10
max_iterations_after_collision_free: 2
max_rollouts: 10#100
min_rollouts: 10
num_rollouts_per_iteration: 10#20

# STOMP (optional)
use_noise_adaptation: true
write_to_file: false
use_openmp: false

noise_coefficients:
 - group_name: right_arm
   stddev: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
   min_stddev: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
   decay:  [0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999]

features: 
- class: stomp_moveit_interface/ObstacleAvoidanceFeature
  collision_clearance: 0.02
